mysql: # docker
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306
  database: goshop
  charset: utf8mb4

consul: # docker
  host: 127.0.0.1
  port: 8500
  scheme: http

gateway-service:
  host: 192.168.1.145
  port: 8080

login-service:
  host: 192.168.1.145
  port: 49000

product-service:
  host: 192.168.1.145
  port: 49100

cart-service:
  host: 192.168.1.145
  port: 49200

auth-service:
  host: 192.168.1.145
  port: 49300
